org: tugzera
app: nestjs-serverless
service: nestjs-serverless

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  individually: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
