org: tugzera
app: nestjs-serverless
service: nestjs-serverless

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    description: Test
    events:
      - http:
          path: hello
          method: get
